version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    networks: 
      - net
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db
  alpr4j:
    container_name: alpr4j
    build: ./alpr4j
    networks: 
      - net
    ports:
      - 8080:8080
  vehiclespy:
    container_name: vehiclespy
    build: ./vehiclespy
    environment:
      MONGODB_DATABASE: vehicles
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongopwd
      MONGODB_HOSTNAME: db
    networks:
      - net
    ports:
      - 5001:5001
  anpr-ng:
    container_name: anpr-ng
    build: ./anpr-ng
    networks:
      - net
    ports:
      - 4000:4000
networks:
  net:
volumes: 
  data: