version: '3.4'

services:
  cateyealpr:
    image: cateye-alpr:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    # networks:
    #   - net
    ports:
      - 5000:5000
      - 5556:5556
    # volumes:
    # - "/etc/timezone:/etc/timezone:ro"
    # - "/etc/localtime:/etc/localtime:ro"
