version: '3.7'
services:
  dev:
    container_name: dev
    build: .
    tty: true
    networks: 
      - dev
    ports: 
      - 8080:8080
      - 8081:8081
      - 80:80
      - 3000:3000
      - 4000:4000
      - 4200:4200
      - 5000:5000
      - 5001:5001
      - 5002:5002
networks:
  dev: